controller:
  hostPort:
    enabled: true
  service:
    type: ClusterIP
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  extraArgs:
    enable-ssl-passthrough: ""
  
  admissionWebhooks:
    patch:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"