#!/bin/bash

if kind get clusters -q | grep crossplane; then
  kind export kubeconfig --name crossplane
  exit 0
fi

cd "$(dirname "$0")" || exit

cd ..

workspaceDir="$PWD"

cd - > /dev/null || exit

# shellcheck source=/dev/null
source "$workspaceDir"/credentials

cat <<EOF | kind create cluster --name crossplane --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.95.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: true
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /var/lib/kubelet/config.json
    hostPath: "$HOME/.docker/config.json"
  extraPortMappings:
    - containerPort: 443
      hostPort: 443
    - containerPort: 80
      hostPort: 80
EOF

kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml

cat << EOF | kubectl create -f-
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 10.95.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()

---

# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}
EOF

kubectl wait --for condition=ready pod --namespace kube-system --all --timeout 300s

helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update
helm install crossplane \
--namespace crossplane-system \
--create-namespace \
crossplane-stable/crossplane \
--wait

kubectl wait --for condition=ready pod --namespace crossplane-system --all --timeout 300s

kubectl apply -f https://raw.githubusercontent.com/irizzante/crossplane/main/crossplane/configurations/gitops.yaml

sleep 10

kubectl delete configuration gitops

kubectl wait --for condition=ready pod --namespace crossplane-system --all --timeout 300s

SA=$(kubectl -n crossplane-system get sa -o name | grep provider-kubernetes | sed -e 's|serviceaccount\/|crossplane-system:|g')
kubectl create clusterrolebinding provider-kubernetes-admin-binding --clusterrole cluster-admin --serviceaccount="${SA}"

SA=$(kubectl -n crossplane-system get sa -o name | grep provider-helm | sed -e 's|serviceaccount\/|crossplane-system:|g')
kubectl create clusterrolebinding provider-helm-admin-binding --clusterrole cluster-admin --serviceaccount="${SA}"

helm repo add argo https://argoproj.github.io/argo-helm
helm upgrade --install argocd --wait -n argocd -f "$workspaceDir"/argocd/values/argocd.yaml --create-namespace argo/argo-cd --version 5.41.1

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm upgrade --install nginx --wait -n nginx -f "$workspaceDir"/argocd/values/nginx.yaml --create-namespace ingress-nginx/ingress-nginx

kubectl create ns port

kubectl -n crossplane-system create secret generic gitlab-secret --from-literal=token="$gitlabToken"

cat << EOF | kubectl apply -f-
apiVersion: v1
kind: Secret
metadata:
  name: github-provider
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: "{\"token\":\"$gitHubPat\",\"owner\":\"$gitHubOwner\"}"
EOF

kubectl apply -f "$workspaceDir"/platform/
