apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xapps.irizzant.it
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: irizzant.it/v1alpha1
    kind: XApp
  resources:
    - name: github-repo
      base:
        apiVersion: repo.github.upbound.io/v1alpha1
        kind: Repository
        metadata:
          name: #patched
        spec:
          providerConfigRef:
            name: github-provider
          forProvider:
            visibility: public
            gitignoreTemplate: #patched
            template:
            - owner: #patched
              repository: #patched

      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
      - fromFieldPath: spec.language
        toFieldPath: spec.forProvider.gitignoreTemplate
      - fromFieldPath: spec.template.owner
        toFieldPath: spec.forProvider.template[0].owner
      - fromFieldPath: spec.template.repository
        toFieldPath: spec.forProvider.template[0].repository

    - name: argocd-app
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: #patched
        spec:
          providerConfigRef:
            name: #patched
          forProvider:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: #patched
              finalizers:
                - resources-finalizer.argocd.argoproj.io
            spec:
              destination:
                name: #patched
                namespace: #patched
              source:
                path: argocd
                repoURL: #patched
                targetRevision: HEAD
              sources: []
              project: default
              syncPolicy:
                automated:
                  prune: true
                  selfHeal: true
                  allowEmpty: true
                syncOptions:
                  - CreateNamespace=true
                  - PruneLast=true

      patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.providerConfigRef.name
      - type: CombineFromComposite
        policy:
          fromFieldPath: Required
        toFieldPath: metadata.name
        combine:
          variables:
            - fromFieldPath: spec.id
            - fromFieldPath: spec.language
          strategy: string
          string:
            fmt: "%s-%s"
      - type: CombineFromComposite
        policy:
          fromFieldPath: Required
        toFieldPath: spec.forProvider.metadata.name
        combine:
          variables:
            - fromFieldPath: spec.id
            - fromFieldPath: spec.language
          strategy: string
          string:
            fmt: "%s-%s"
      - fromFieldPath: spec.cluster
        toFieldPath: spec.forProvider.spec.destination.name
      - fromFieldPath: spec.id
        toFieldPath: spec.forProvider.spec.destination.namespace
      - fromFieldPath: spec.gitOpsRepo
        toFieldPath: spec.forProvider.spec.source.repoURL

