apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gitlab-provider
spec:
  baseURL: https://production.eng.it/gitlab
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gitlab-secret
      key: token