apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: github-provider
  annotations:
      argocd.argoproj.io/sync-wave: "-4"
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-provider
      namespace: crossplane-system
      key: credentials
