apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: github-provider
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-provider
      namespace: crossplane-system
      key: credentials
