apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvclusters.irizzant.it
spec:
  group: irizzant.it
  names:
    kind: XVCluster
    plural: xvclusters
  claimNames:
    kind: VCluster
    plural: vclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: ID of this VCluster, used as reference by other objects
                gitOpsRepo:
                  type: string
                  description: GitOps repo URL
                gitOpsPath:
                  type: string
                  description: GitOps repo path
                gitOpsSecret:
                  type: string
                  description: Name of the secret in the host cluster to replicate in the VCluster. Can be used to configure a ClusterStore for external-secrets
              required:
                - id
                - gitOpsRepo
                - gitOpsPath
                - gitOpsSecret