apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/irizzante/port-demo.git'
    path: crossplane
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
