apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-bitwarden
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bitwarden
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/components/externalsecrets-bitwarden/cluster-secret-store
    repoURL: 'https://github.com/irizzante/cluster-addons.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
