apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: eso
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.1
    chart: external-secrets
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
