apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  annotations:
      argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.8.1
    chart: ingress-nginx
    helm:
      valueFiles:
      - $values/argocd/values/nginx.yaml
  - repoURL: 'https://github.com/irizzante/port-demo.git'
    targetRevision: HEAD
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
