apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: port-exporter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://port-labs.github.io/helm-charts'
    targetRevision: 0.1.18
    chart: port-k8s-exporter
    helm:
      parameters: []
      values: |-
        secret:
          useExistingSecret: true
          name: port
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
