apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: port-exporter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: port
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://port-labs.github.io/helm-charts'
    targetRevision: 0.2.31
    chart: port-k8s-exporter
    helm:
      valueFiles:
      - $values/argocd/values/port.yaml
  - repoURL: 'https://github.com/irizzante/port-demo.git'
    targetRevision: HEAD
    ref: values         
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
