apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vclusters
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: vclusters
    repoURL: 'https://github.com/irizzante/port-demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
