apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvclusters.irizzant.it
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: irizzant.it/v1alpha1
    kind: XVCluster

  resources:
    - name: vcluster-helm-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: #patched
          annotations:
            crossplane.io/external-name: # patched
        spec:
          rollbackLimit: 3
          providerConfigRef:
            name: helm-provider
          forProvider:
            namespace: #patched
            chart:
              name: vcluster
              repository: https://charts.loft.sh
              version: "0.15.2"
            values:
              isolation:
                enabled: true
              sync:
                nodes:
                  enabled: true
                  syncAllNodes: true
                persistentvolumes:
                  enabled: true
                ingresses:
                  enabled: true
                networkpolicies:
                  enabled: true
              syncer:
                extraArgs: [] # patched
              init:
                helm:
                - chart:
                    name: argo-cd
                    repo: https://argoproj.github.io/argo-helm
                    version: 5.41.1
                  release:
                    name: argocd
                    namespace: argocd

          writeConnectionSecretToRef:
            name: # patched
            namespace: crossplane-system
          connectionDetails:
          - apiVersion: v1
            kind: Secret
            name: # patched
            namespace: # patched
            fieldPath: data.config
            toConnectionSecretKey: config
            skipPartOfReleaseCheck: true
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-vcluster"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.namespace
          transforms:
            - type: string
              string:
                fmt: "%s-vcluster"
        - fromFieldPath: spec.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          policy:
            fromFieldPath: Required
        - type: CombineFromComposite
          policy:
            fromFieldPath: Required
          fromFieldPath: spec.id
          toFieldPath: spec.forProvider.values.syncer.extraArgs[0]
          combine:
            variables:
              - fromFieldPath: spec.id
              - fromFieldPath: spec.id
            strategy: string
            string:
              fmt: "--out-kube-config-server=https://%s.%s-vcluster.svc.cluster.local"
        - type: CombineFromComposite
          policy:
            fromFieldPath: Required
          fromFieldPath: spec.id
          toFieldPath: spec.forProvider.values.syncer.extraArgs[1]
          combine:
            variables:
              - fromFieldPath: spec.id
              - fromFieldPath: spec.id
            strategy: string
            string:
              fmt: "--tls-san=%s.%s-vcluster.svc.cluster.local"
        - fromFieldPath: spec.id
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "vc-%s"
        - fromFieldPath: spec.id
          toFieldPath: spec.connectionDetails[0].name
          transforms:
            - type: string
              string:
                fmt: "vc-%s"
        - fromFieldPath: spec.id
          toFieldPath: spec.connectionDetails[0].namespace
          transforms:
            - type: string
              string:
                fmt: "%s-vcluster"

    - name: helm-provider-vcluster
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        metadata:
          name: #patched
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: #patched
              key: config
              name: #patched

      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-helm-provider"
        - fromFieldPath: spec.id
          toFieldPath: spec.credentials.secretRef.namespace
          transforms:
            - type: string
              string:
                fmt: "%s-vcluster"
        # This ProviderConfig uses the above VCluster's connection secret as
        # its credentials secret.
        - fromFieldPath: spec.id
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: "vc-%s"
      readinessChecks:
        - type: None

    - name: k8s-provider-vcluster
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        metadata:
          name: #patched
        spec:
          credentials:
            source: Secret
            secretRef:
              namespace: #patched
              key: config
              name: #patched

      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-kubernetes-provider"
        - fromFieldPath: spec.id
          toFieldPath: spec.credentials.secretRef.namespace
          transforms:
            - type: string
              string:
                fmt: "%s-vcluster"
        # This ProviderConfig uses the above VCluster's connection secret as
        # its credentials secret.
        - fromFieldPath: spec.id
          toFieldPath: spec.credentials.secretRef.name
          transforms:
            - type: string
              string:
                fmt: "vc-%s"
      readinessChecks:
        - type: None
    
    - name: secret-for-secret-store
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: #patched
        spec:
          references:
          # Use patchesFrom to patch field from other k8s resource to this object
          - patchesFrom:
              apiVersion: v1
              kind: Secret
              name: #patched
              namespace: kube-system
              fieldPath: data
            toFieldPath: data
          providerConfigRef:
            name: #patched
          forProvider:
            manifest:
              apiVersion: v1
              data: #patched
              kind: Secret
              metadata:
                name: #patched
                namespace: kube-system
              type: Opaque
      
      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
        - type: string
          string:
            fmt: "%s-secret-store-secret"
      - fromFieldPath: spec.id
        toFieldPath: spec.providerConfigRef.name
        transforms:
          - type: string
            string:
              fmt: "%s-kubernetes-provider"
      - fromFieldPath: spec.gitOpsSecret
        toFieldPath: spec.references[0].patchesFrom.name
      - fromFieldPath: spec.gitOpsSecret
        toFieldPath: spec.forProvider.manifest.metadata.name
    
    - name: argocd-platform-application
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: #patched
        spec:
          providerConfigRef:
            name: #patched
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: platform
                namespace: argocd
                finalizers:
                  - resources-finalizer.argocd.argoproj.io
              spec:
                project: default
                source:
                  targetRevision: HEAD
                  path: #patched
                  repoUrl: #patched
                destination:
                  server: https://kubernetes.default.svc
                  namespace: argocd
                syncPolicy:
                  automated:
                    selfHeal: true
                    prune: true
                    allowEmpty: true
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-argocd-platform-application"
        - fromFieldPath: spec.id
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-kubernetes-provider"
        - fromFieldPath: spec.gitOpsPath
          toFieldPath: spec.forProvider.manifest.spec.source.path
        - fromFieldPath: spec.gitOpsRepo
          toFieldPath: spec.forProvider.manifest.spec.source.repoURL
