apiVersion: irizzant.it/v1alpha1
kind: GitOps
metadata:
    name: gitops
    annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  id: vcluster-CLUSTER_NAME
  kubeConfig:
    secretKey: config
    secretName: vc-CLUSTER_NAME
  gitOpsRepo: https://github.com/irizzante/port-demo.git
  gitOpsPath: GITOPS_PATH
  gitOpsSecret: gitlab-secret