apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gitlab
spec:
  provider:
    gitlab:
      groupIDs: 
      - "18304"
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            namespace: kube-system
            key: token