apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: port-credentials
  namespace: port
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab
  target:
    name: port
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: port