apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: port-credentials
  namespace: port
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    type: Opaque
    name: port
    deletionPolicy: Delete
    data:
      PORT_CLIENT_ID: |-
        {{ .username }}
      PORT_CLIENT_SECRET: |-
        {{ .password }}

  data:
  - secretKey: username
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: dcce73b9-e405-49d9-a6b4-b1180096abda
      property: username
  - secretKey: password
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: dcce73b9-e405-49d9-a6b4-b1180096abda
      property: password