apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aaaabbb
  namespace: default
spec:
  dataFrom:
    - extract:
        key: port
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab
  target:
    creationPolicy: Owner
    name: port
