apiVersion: irizzant.it/v1alpha1
kind: GitOps
metadata:
    name: gitops
    annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  providerConfigName:
    helm: test
    kubernetes: test
  gitOpsRepo: https://github.com/irizzante/port-demo.git
  gitOpsPath: vcluster
  gitOpsSecret: gitlab-secret
