name: Create an app
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "The name of the cluster"
      language:
        required: true
        description: "The programming language"
      team:
        required: true
        description: "The team the app belongs to"
      environment:
        required: true
        description: "The cluster the app is deployed in"
      port_payload:
        required: true
        description: "The Port payload"
        
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create app
        run: |
          cp templates/app.yaml argocd/${{ inputs.name }}-${{ inputs.environment }}-app.yaml
          yq || true
          sed -i 's@CLUSTER_NAME@${{ inputs.environment }}@g' argocd/${{ inputs.name }}-${{ inputs.environment }}-app.yaml
          sed -i 's@APP_NAME@${{ inputs.name }}@g' argocd/${{ inputs.name }}-${{ inputs.environment }}-app.yaml
          sed -i 's@TEAM@${{ inputs.team }}@g' argocd/${{ inputs.name }}-${{ inputs.environment }}-app.yaml
          sed -i 's@LANGUAGE@${{ inputs.language }}@g' argocd/${{ inputs.name }}-${{ inputs.environment }}-app.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions