name: Create a cluster
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "The name of the cluster"
      domain:
        required: true
        description: "The domain of the cluster"
      team:
        required: true
        description: "The team the cluster belongs to"
      port_payload:
        required: true
        description: "The Port payload"
        
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create cluster
        run: |
          mkdir -p vcluster/${{ inputs.name }}
          cp templates/argocd-vcluster-app.yaml argocd/vcluster-apps-${{ inputs.name }}-app.yaml
          yq --inplace ".metadata.name = \"vcluster-apps-${{ inputs.name }}\"" argocd/vcluster-apps-${{ inputs.name }}-app.yaml
          yq --inplace ".spec.source.path = \"vcluster/${{ inputs.name }}\"" argocd/vcluster-apps-${{ inputs.name }}-app.yaml
          cp templates/vcluster.yaml vcluster/${{ inputs.name }}/
          yq --inplace ".metadata.name = \"${{ inputs.name }}\"" vcluster/${{ inputs.name }}/vcluster.yaml
          yq --inplace ".spec.writeConnectionSecretToRef.name = \"${{ inputs.name }}-vc\"" vcluster/${{ inputs.name }}/vcluster.yaml
          yq --inplace ".spec.id = \"${{ inputs.name }}\"" vcluster/${{ inputs.name }}/vcluster.yaml
          yq --inplace ".spec.hostDomain = \"${{ inputs.domain }}\"" vcluster/${{ inputs.name }}/vcluster.yaml
          yq --inplace ".spec.team = \"${{ inputs.team }}\"" vcluster/${{ inputs.name }}/vcluster.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions