name: Delete a cluster
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "The name of the cluster"
      port_payload:
        required: true
        description: "The Port payload"
      
jobs:
  delete-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete cluster
        run: |
          rm argocd/argocd-vcluster-${{ inputs.name }}-app.yaml
          rm -rf vcluster/${{ inputs.name }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions