name: Delete a vcluster
on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: false
        description: "The Port payload"
      
jobs:
  delete-vcluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract entity id
        id: entity-id
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo '${{ inputs.port_payload }}' | jq .payload.entity.identifier -r

      - name: Delete vcluster
        run: |
          echo ${{ steps.entity-id.outputs.value }}
          rm argocd/vcluster-apps-${{ steps.entity-id.outputs.value }}-app.yaml
          rm -rf vcluster/${{ steps.entity-id.outputs.value }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions