name: Delete a vcluster
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "The name of the vcluster"
      port_payload:
        required: false
        description: "The Port payload"
      
jobs:
  delete-vcluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete vcluster
        run: |
          rm argocd/argocd-vcluster-${{ inputs.name }}-app.yaml
          rm -rf vcluster/${{ inputs.name }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions